In [76]:
import pandas as pd
import numpy as np

In [77]:
df = pd.read_csv("data/credit_risk_dataset.csv")

df.head()

,customer_id,age,gender,employment_status,annual_income,account_age_months,avg_monthly_balance,num_deposits_per_month,avg_deposit_amount,debit_card_usage_frequency,...,online_transfer_frequency,atm_withdrawal_frequency,credit_score,num_open_loans,total_outstanding_debt,late_payment_count,loan_default_history,fraud_flag,loan_application_amount,credit_risk
0,CUST_00000,58,Male,Unemployed,58137.751192,115,524.679407,1,171.342369,49,...,16,1,539,5,14435.423445,2,0,0,15510.576882,1
1,CUST_00001,48,Male,Self-Employed,26174.922827,32,2635.203357,1,985.607164,1,...,1,2,494,5,11263.099341,2,0,0,14819.436498,1
2,CUST_00002,34,Other,Unemployed,75566.837265,14,2334.341061,9,994.310119,42,...,5,6,437,3,15017.144132,5,0,0,10909.806507,1
3,CUST_00003,62,Male,Self-Employed,35197.961516,179,2425.384332,10,366.115346,4,...,7,7,809,1,12626.138476,2,0,0,500.000000,0
4,CUST_00004,27,Female,Self-Employed,12136.998349,225,10.000000,8,786.752258,16,...,16,3,522,1,13576.704320,4,0,0,9514.591618,1

In [78]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customer_id                 5000 non-null   str
 1   age                         5000 non-null   int64
 2   gender                      5000 non-null   str
 3   employment_status           5000 non-null   str
 4   annual_income               5000 non-null   float64
 5   account_age_months          5000 non-null   int64
 6   avg_monthly_balance         5000 non-null   float64
 7   num_deposits_per_month      5000 non-null   int64
 8   avg_deposit_amount          5000 non-null   float64
 9   debit_card_usage_frequency  5000 non-null   int64
 10  debit_card_spending         5000 non-null   float64
 11  mobile_banking_logins       5000 non-null   int64
 12  online_transfer_frequency   5000 non-null   int64
 13  atm_withdrawal_frequency    5000 non-null   int64
 14  credit_score                5000 non-null   int64
 15  num_open_loans              5000 non-null   int64
 16  total_outstanding_debt      5000 non-null   float64
 17  late_payment_count          5000 non-null   int64
 18  loan_default_history        5000 non-null   int64
 19  fraud_flag                  5000 non-null   int64
 20  loan_application_amount     5000 non-null   float64
 21  credit_risk                 5000 non-null   int64
dtypes: float64(6), int64(13), str(3)
memory usage: 859.5 KB

,age,annual_income,account_age_months,avg_monthly_balance,num_deposits_per_month,avg_deposit_amount,debit_card_usage_frequency,debit_card_spending,mobile_banking_logins,online_transfer_frequency,atm_withdrawal_frequency,credit_score,num_open_loans,total_outstanding_debt,late_payment_count,loan_default_history,fraud_flag,loan_application_amount,credit_risk
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.00000
mean,44.666600,49870.073961,121.226800,1500.912691,5.542000,800.663464,24.424800,500.284845,39.028000,9.660600,4.55720,599.328200,2.480800,12173.548537,3.46940,0.097400,0.028600,8149.415730,0.76580
std,14.384312,17831.984829,68.325584,772.243462,3.424118,341.229714,14.395172,245.167842,23.039457,5.858248,2.89109,174.345499,1.698649,5993.358818,2.29332,0.296531,0.166696,4309.579471,0.42354
min,20.000000,10000.000000,3.000000,10.000000,0.000000,20.000000,0.000000,0.000000,0.000000,0.000000,0.00000,300.000000,0.000000,0.000000,0.00000,0.000000,0.000000,500.000000,0.00000
25%,32.000000,37633.483896,62.000000,958.522753,3.000000,559.312932,12.000000,328.342032,19.000000,4.000000,2.00000,447.000000,1.000000,8076.729416,1.00000,0.000000,0.000000,4993.481978,1.00000
50%,45.000000,49682.456590,120.500000,1486.067085,6.000000,802.695763,25.000000,498.752458,39.000000,10.000000,5.00000,597.000000,2.000000,12196.804292,3.00000,0.000000,0.000000,8039.116433,1.00000
75%,57.000000,61964.226233,181.000000,2024.758900,9.000000,1033.796072,37.000000,664.056885,58.000000,15.000000,7.00000,753.000000,4.000000,16279.963090,5.00000,0.000000,0.000000,11160.811371,1.00000
max,69.000000,113793.170197,239.000000,4818.316040,11.000000,1925.380969,49.000000,1379.491843,79.000000,19.000000,9.00000,899.000000,5.000000,32433.862750,7.00000,1.000000,1.000000,25622.344659,1.00000

In [79]:
df_clean = df.drop(columns=[
    "customer_id",
    "loan_default_history",
    "fraud_flag",
    "credit_score"
])

In [80]:
df_clean = pd.get_dummies(df_clean, drop_first=True)

df_clean.head()

,age,annual_income,account_age_months,avg_monthly_balance,num_deposits_per_month,avg_deposit_amount,debit_card_usage_frequency,debit_card_spending,mobile_banking_logins,online_transfer_frequency,atm_withdrawal_frequency,num_open_loans,total_outstanding_debt,late_payment_count,loan_application_amount,credit_risk,gender_Male,gender_Other,employment_status_Self-Employed,employment_status_Unemployed
0,58,58137.751192,115,524.679407,1,171.342369,49,768.877511,9,16,1,5,14435.423445,2,15510.576882,1,True,False,False,True
1,48,26174.922827,32,2635.203357,1,985.607164,1,580.287785,9,1,2,5,11263.099341,2,14819.436498,1,True,False,True,False
2,34,75566.837265,14,2334.341061,9,994.310119,42,564.013508,36,5,6,3,15017.144132,5,10909.806507,1,False,True,False,True
3,62,35197.961516,179,2425.384332,10,366.115346,4,838.489200,31,7,7,1,12626.138476,2,500.000000,0,True,False,True,False
4,27,12136.998349,225,10.000000,8,786.752258,16,462.495522,35,16,3,1,13576.704320,4,9514.591618,1,False,False,True,False

In [81]:
X = df_clean.drop(columns=["credit_risk"])
y = df_clean["credit_risk"]

In [82]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [83]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

In [84]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=2000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=2000)

In [85]:
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

In [86]:
from sklearn.metrics import accuracy_score, roc_auc_score

print("Accuracy:", accuracy_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))

Accuracy: 0.757
ROC-AUC: 0.8320967732505451

In [87]:
feature_importance = pd.DataFrame({
    "feature": X.columns,
    "importance": model.coef_[0]
})

feature_importance.sort_values(by="importance", ascending=False)

                            feature  importance
13               late_payment_count    1.522651
10         atm_withdrawal_frequency    0.056604
11                   num_open_loans    0.055781
5                avg_deposit_amount    0.054362
8             mobile_banking_logins    0.046404
18     employment_status_Unemployed    0.043931
15                      gender_Male    0.041460
16                     gender_Other    0.040789
14          loan_application_amount    0.029913
2                account_age_months    0.028309
0                               age    0.027474
12           total_outstanding_debt    0.014128
1                     annual_income    0.010230
3               avg_monthly_balance    0.004118
6        debit_card_usage_frequency   -0.011822
7               debit_card_spending   -0.018085
4            num_deposits_per_month   -0.020916
9         online_transfer_frequency   -0.022631
17  employment_status_Self-Employed   -0.026993